#!/usr/bin/env python

import sys
print(sys.path)
from mcm_testarea.submitter import Submitter

prepid_list = ['HIG-RunIISummer15wmLHEGS-03434']
sub = Submitter(prepid_list=prepid_list)
pprint(sub.submission_settings)
